# ------------------------------------------------------------------------------
# Generate a data flow manifest
# Then open a PR to incorporate them into the repo
# ------------------------------------------------------------------------------
name: generate-dataflow-manifest
on:
  workflow_dispatch:
    inputs:
      data_model:
        description: URL to a jsonld data model file
        required: true
      community_dir:
        description: Community directory
        required: true

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      SCHEMATIC_BASE_URL: https://schematic.api.sagebionetworks.org
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip libicu-dev libcurl4-openssl-dev

      - name: Install R packages
        run: |
          options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/xenial/latest", 
            getOption("repos")))
          install.packages(c("stringi", "jsonlite", "dplyr", "remotes", "curl","httr"))
          remotes::install_github("Sage-Bionetworks/dfamodules", ref = "dev")
        shell: Rscript {0}

      - name: Write environment variables
        shell: bash
        run: |
          echo 'data_model=${{ inputs.data_model }}' >> $GITHUB_ENV
          echo 'community_dir=${{ inputs.community_dir }}' >> $GITHUB_ENV

      - name: Generate Data Flow manifest
        shell: Rscript {0}
        run: |
          config_path <- file.path("${{ env.community_dir }}", "dfa_config.json")

          dfa_config <- jsonlite::read_json(config_path)

          dataflow_manifest <- tryCatch(
            {
              dfamodules::generate_dataflow_manifest(
                asset_view = dfa_config$dcc$synapse_asset_view,
                schema_url = dfa_config$dcc$data_model_url,
                access_token = "${{ secrets.SYNAPSE_PAT }}",
                na_replace = "",
                base_url = "${{ env.SCHEMATIC_BASE_URL }}")
            },
            error = function(e) {
              stop("ERROR: Data Flow manifest generation has failed")
            }
          )

          message("Successfully generated Data Flow Manifest")

          filepath <- file.path("${{ env.community_dir }}", "synapse_storage_manifest_dataflow.csv")

          message("Writing manifest to ", filepath)

          write.csv(
            x = dataflow_manifest,
            file = filepath,
            row.names = FALSE
          )

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: ${{ env.community_dir }} Data Flow manifest generated
          body: |
            Data flow manifest generated by [generate_manifest](https://github.com/Sage-Bionetworks/data_flow_config/actions/workflows/generate_manifest.yml)
          delete_branch: true
          branch-suffix: timestamp
          add-paths: ${{ env.community_dir }}/synapse_storage_manifest_dataflow.csv
